### ISSUE TITLE
Grid refresh + splitter

### ISSUE THREAD

**Issue by SIRprise** [ChrisRfr/IceDesign#9]
Thanks for adding undo!!!

The Checkbox for the grid seems not to refresh and I can have a mix if I resize the window:
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/e01130d9-0903-43de-96db-3173b103761c)

It's a while ago I tried to add a vertical splitter, and add a horizontal splitter to the right container of the 1st splitter. I don't remember if I could do it. I just tried to add two Container-Gadgets, add a vertical splitter, deselect, select via dropdown and tried to move it and I can't. Then I added a button and used undo and I could move the splitter with the containers.
The lock-option (above hide and tooltip) also seems to have a strange behaviour (on my PC):
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/2b05a1b5-630c-4ed3-af29-4267b0146866)
After click to anchor right and lock checkboxes and deselect the control, I cannot get the options back if I select it. But now I found the problem&solution: If I deselect the lock again, the menu is not immediatly updated ("Lock & Proportional" is missing ... and I could have found a better translation..."Verankerung & Verhältnisse" or something like that):
![grafik](https://github.com/ChrisRfr/IceDesign/assets/5807446/6d39fc08-31b7-4f1d-9fde-be5a123308b7)
But if I deselect the control and select it again, the menu has all options again.

Sometimes I have problems to see the settings-menu or the control list because it seem to have black font color or something. Maybe that kind of refresh-problems are on my computer only.
Could you make tutorial or demo videos some day, so I can get a feeling how to use the tool the right way and how to build complex GUIs? Sometimes I feel I should use another order/sequence of adding gadgets and configuring it. For example: How can I add a vertical splitter with container left and on the right side another splitter with the upper part should be a container and the lower part a panel. Do I have to create the horizontal splitter first?

**Comment by ChrisRfr** [comment]
Hi SIRprise,

> The Checkbox for the grid seems not to refresh and I can have a mix if I resize the window

IceDesign works in levels: the window is one level, and each container is another level. Each level has its own Canvas for drawing the grid and child gadgets  and only the current level's Canvas is active and redrawn.
When you activate or deactivate the grid, only the current level is updated, the other levels remain as they were and will be redrawn as soon as you get inside.

**Comment by ChrisRfr** [comment]
To select and move a Splitter, you can use the area between the 2 child gadgets, the separator.
I know it's not easy, it's quite small, only 7 pixels, the 2 child gadgets take up most of the space.
Otherwise, to select the Splitter, it may be easier to select one of the 2 children, and use Esc (or the Close Container button), to close the current level and return to the previous one, the Splitter.

I didn't quite understand your concern with the Lock property. For a splitter, the 2 child gadgets are locked, they can't be moved, their positions and sizes are calculated according to the Splitter's size and position.

The Locked property (above Hidden) is only for locking gadgets in the Design area to prevent them from being moved without any impact on the generated code.
"Lock & Proportional" is something else, these properties are only for the generated code to lock the Gadgets to the Left, Right, Top and Bottom borders or to get a proportional size, when the window is resized.

For the Splitter, maybe you can watch this demo: https://github.com/ChrisRfr/IceDesign/blob/master/gif_demo/Demo_Splitter.gif

**Comment by SIRprise** [comment]
Hi Chris,
oh ok, the levels make sense. And: Thank you for the gifs - I didn't read the last sentence of the repo readme.md. sorry! The videos are very helpful!!!

The thing with the locked property is, that it hides the "Lock & Proportional"-settings and doesn't immediatly unhide them if dechecked. The property list seems not to be updated. But now I understand, that it is for hiding the properties only.
